### ISSUE TITLE
can't ssh to new created ubuntu VM as root

### ISSUE THREAD

**Issue by Emi94** [newroco/vmbuilder#3]
When a new ubuntu VM is created i can't ssh to it as root because of line "PermitRootLogin prohibit-password" from /etc/ssh/sshd_config file.

One option would be to create a template for the /etc/ssh/sshd_config file with line "PermitRootLogin prohibit-password" changed to "PermitRootLogin yes". It would also need a function for the new template added in https://github.com/newroco/vmbuilder/blob/master/VMBuilder/plugins/ubuntu/dapper.py and this function called from https://github.com/newroco/vmbuilder/blob/master/VMBuilder/plugins/ubuntu/distro.py

**Comment by putt1ck** [comment]
For general purpose service-providing VMs seems best to use root for initial login and disable during setup of the VM's services; can see a security benefit from not having root as a usable account for non-technical end user systems, but not servers. Fix sounds good to me.

**Comment by putt1ck** [comment]
Patch submitted, accepted & merged
