### ISSUE TITLE
vmbuilder dist-upgrade fails

### ISSUE THREAD

**Issue by josephbisch** [newroco/vmbuilder#5]
As reported at the following links, users experience issues with the vmbuilder VM failing to dist-upgrade.

https://github.com/devrandom/gitian-builder/issues/139
https://bugs.launchpad.net/ubuntu/+source/vm-builder/+bug/1618899

Possible solutions seem to be [this patch from the Launchpad link](https://launchpadlibrarian.net/305019660/vmbuilder_sudo.patch), or adding `-option=Dpkg::Options::=--force-confnew` to the `apt-get dist-upgrade` call as both links mention.

**Comment by putt1ck** [comment]
@Emi94 any view on which solution is best? Half inclined to remove the update during build as it should/is going to happen when the machine is customised for use, but can see the case where the machine is being deployed ready for production use.

**Comment by Emi94** [comment]
both solutions work, but from what i read here https://bugs.launchpad.net/ubuntu/+source/vm-builder/+bug/1618899, a template for /etc/sudoers is not really needed, the one used now is out of date anyway so i guess we could remove the line where /etc/sudoers is installed from template.

**Comment by putt1ck** [comment]
+1 for remove the line

**Comment by Emi94** [comment]
Fixed with patch #7
